Repository nikkolas-james-irwin/big-data-systems-course-project, pull requests merged in 2020-05, with the labels that each got.

#44 Updated README
  README.md
Labels: documentation

#45 Features/rating time series
  recommender.py
  vis.py
Labels: apache-spark, data visualization

#46 Features/prediction vis
  recommender.py
  vis.py
Labels: apache-spark, data visualization

#47 Features/helpful review vis
  recommender.py
  vis.py
Labels: apache-spark, data visualization

#48 Updated DocStrings
  recommender.py
Labels: documentation

#51 Refactor/chart table updates
  recommender.py
  vis.py
Labels: data visualization, enhancement, python, refactoring

#52 Fixed Histogram Bug, Fixed Table Ratios
  recommender.py
  vis.py
Labels: bug, refactoring
