Repository nikkolas-james-irwin/big-data-systems-course-project, pull requests merged in 2020-04, with the labels that each got.

#9 Adding Dockerfile and Conda Environmental File
  Dockerfile
  environment.yml
Labels: docker, enhancement

#12 Initial commit of recommender example
  recommender.py
Labels: apache-spark, data visualization

#14 Updated README
  README.md
Labels: documentation

#15 Updated Example Usage Section
  README.md
Labels: documentation, enhancement

#16 Updated Comments
  .dockerignore
  .gitignore
  Dockerfile
  environment.yml
Labels: documentation

#17 Added Link To DockerHub Image
  README.md
Labels: documentation

#18 Fix Grammar
  README.md
Labels: documentation

#19 Added Docker Pull Command
  README.md
Labels: documentation

#28 Added Arguments to Program
  recommender.py
Labels: enhancement

#32 Fixed Console Output Spacing Issues
  recommender.py
Labels: bug

#36 Fixed Python Command Line Argument Formatting
  recommender.py
Labels: bug, help wanted

#40 Updated README
  README.md
Labels: documentation

#41 Updated README
  README.md
Labels: documentation

#42 Features/summary vis
  recommender.py
  vis.py
Labels: apache-spark, data visualization
